---
title: "My 101 Games for the Nintendo Switch - An Interactive Visualization"
author: Christoph Blapp
format: 
  html:
    backgroundcolor: '#FFF8DC'
editor: visual
---

```{r,include=FALSE}
library(ggplot2)
library(dplyr)
library(plotly)
library(ggbeeswarm)

data_raw <- read.csv("~/Documents/collection_figure/collection.csv")

data<-data_raw%>%
  mutate(
    cat=case_when(
      cat==1~"Nintendo",
      cat==2~"Other Big\nStudios",
      cat==3~"Indie",
      cat==4~"Retro"
    )%>%
      factor(levels = c(
        "Nintendo",
        "Other Big\nStudios",
        "Indie",
        "Retro"
        ))
  )%>%
  group_by(cat,rating)%>%
  mutate(
    rat1=rating,
    rat2=case_when(#manual adjustment
      n()<4~rating,
      n()<10~rating+sample(c(-0.1,0.1),n(),replace=T),
      TRUE~rating+sample(c(-0.2,0,0,0.2),n(),replace=T)
    )
    )%>%
  ungroup()

labels=c(
  "All-Time-Favorite",
  "Fantastic",
  "Pretty good",
  "Not my thing",
  "I have a deep\npersonal grudge against\nthis videogame",
  "Can't judge yet"
)
```

```{r,echo=FALSE}
fig<-(
  data%>%
    ggplot(aes(x=cat,y=-rat2,key=Name))+
      geom_beeswarm(col="deeppink3",shape=18,cex=2.5)+
      theme_minimal()+
      scale_y_continuous("",breaks = -(1:6),labels = labels)+
      scale_x_discrete("")+
      geom_hline(yintercept=-5.5,col="black")+
    theme(
      panel.grid.major.x = element_blank(),
      plot.background = element_rect(fill="cornsilk"),
      panel.background = element_rect(fill = NA),
      panel.grid.major.y = element_line(color="cornsilk3")
      )
    )%>%
  ggplotly(tooltip="key",showlegend=FALSE)

fig$x$data[[1]]$text<-stringr::str_remove(
  fig$x$data[[1]]$text,
  "Name: "
)
fig
```

